### ISSUE TITLE
message.execution.m_orderId always 2**31-1

### ISSUE THREAD

**Issue by expectedvalue073** [blampe/IbPy#36]
It seems to never be set.

**Comment by DMTSource** [comment]
I am unsure of the context in which you are trying to access the orderId.
It appears to be returning some bad values. Perhaps they are not being set
correctly?

If you are attempting to create orders from outside TWS, you need to
manually handle and set your order ids so that they do not conflict with
TWS or other apis sending orders. One way to do this is to reqest a valid
id before generating the order. This can be done with *reqIDs* prior to an
order, also *nextValidId* might be useful on launch if not redundant.

There is also the challenge of spamming orders, so it can be useful to
modify orders instead of cancling them.

Source:
https://www.interactivebrokers.com/en/software/api/apiguide/java/reqids.htm
https://www.interactivebrokers.com/en/software/api/apiguide/java/nextvalidid.htm

Additional Reading on Order IDs:
https://www.interactivebrokers.com/en/software/api/apiguide/api/api_order_ids.htm
https://www.interactivebrokers.com/en/software/csharp/topics/orders.htm
https://www.interactivebrokers.com/en/software/api/apiguide/api/recommendations.htm

On Thu, Nov 24, 2016 at 11:02 AM, expectedvalue073 <notifications@github.com

**Comment by expectedvalue073** [comment]
This is through running reqExecution and getting the order ids of existing trades.

**Comment by expectedvalue073** [comment]
I dug into it a bit. Printing out the string in readStr for specifically the orderId is actually always 2147483647, so I wonder if IB changed any conventions on their end...

**Comment by expectedvalue073** [comment]
Actually, I am now thinking that executed trades do not have the order ids attached to them, but I am not sure.

**Comment by DMTSource** [comment]
Interesting. Are these orders you created or did they originate in TWS? TWS
orders will have a fixed ID of Zero:

https://www.interactivebrokers.com/en/software/api/apiguide/java/execution.htm

**Comment by expectedvalue073** [comment]
These are orders I manually put in through the phone app, not TWS.

**Comment by DMTSource** [comment]
That must be it. I believe order ID is for local API clients and loses
meaning outside that scope. Can you try the parameter m_permId from that
execution link I posted above.

**Comment by expectedvalue073** [comment]
You are right. permId is what I'm looking for -- it's the same for the same order, but for potentially numerous executions against the same order.
